### ISSUE TITLE
"backstagePostThreadRenderer" error

### ISSUE THREAD

**Issue by kellersefi** [NothingNaN/YoutubeCommunityScraper#2]
Hello, thanks for building this useful tool. 
I'm getting the following error, consistently, on some channels while others work fine.
 
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yp_dl/yp_dl.py", line 236, in scrape
    self.token = post['continuationItemRenderer']['continuationEndpoint']['continuationCommand']['token']
                 ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'continuationItemRenderer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/yp-dl", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yp_dl/yp_dl.py", line 335, in run
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yp_dl/yp_dl.py", line 239, in scrape
    postRenderer = post['backstagePostThreadRenderer']['post']['backstagePostRenderer']
                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'backstagePostThreadRenderer'
```

Example of a channel that triggers an error: @Rix1Dev
Example of a channel that does not trigger an error: @GameDevRaj

**Comment by NothingNaN** [comment]
Thanks for bringing this to my attention. It seems I didn't handle the case when a YouTube channel has less than 10 posts. Will be fixed soon.
