### ISSUE TITLE
Failing to scrape certain channel

### ISSUE THREAD

**Issue by Comitant** [NothingNaN/YoutubeCommunityScraper#4]
https://www.youtube.com/@PunishingGrayRaven
While scraping that channels posts I get this error:

@PunishingGrayRaven ⠇ 51/70 0:00:00
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Scripts\yp-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\site-packages\yp_dl\yp_dl.py", line 335, in run
    loop.run_until_complete(asyncio.gather(*tasks))
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\-\AppData\Local\Programs\Python\Python311\Lib\site-packages\yp_dl\yp_dl.py", line 231, in scrape
    postRenderer = post['backstagePostThreadRenderer']['post']['backstagePostRenderer']
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'backstagePostRenderer'

**Comment by NothingNaN** [comment]
Looked at it and it seems that one of the posts it tried to scrape was a new type called "sharedPostRenderer". I didn't know they exist. Will be fixed within 48 hours.
